apiVersion: v1

kind: Service

metadata:
    name: backend-service

spec:
    type: NodePort
    ports:
        - targetPort: 8080
          port: 8080
          nodePort: 30006

    selector:
        app: my-backend
        type: backend