apiVersion: v1

kind: Pod

metadata:
    name: test-pvc-pod

spec:
    containers:
        - image: alpine
          name: alpine
          command: ["/bin/sh", "-c"]
          args: ["sleep 30000"]

          volumeMounts:
            - mountPath: /opt
              name : data-volume

    volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: postgres-pvc